In [1]:
import pandas as pd
import xarray as xr
import numpy as np
import os
import glob
import matplotlib.pyplot as plt

In [2]:
files=os.listdir('/directory/')    
path = r'/directory/' # use your path
all_files = glob.glob(path + "/*.file format")

li = []
lid=[]
liy=[]
for filename in all_files:
    dfl = pd.read_csv(filename, index_col=None, header=0)
    df = dfl[(dfl['NO_IRRF']>0.0) & (dfl['NO_IRRF']<5.0)]
    NO_ave= df[['NO_IRRF']].mean()
    dte=df[['DOY']].mean()
    yer=df[['YEAR']].mean()

    li.append(NO_ave)
    lid.append(dte)
    liy.append(yer)

df = pd.concat(li)
dtt=pd.concat(lid)
yrr=pd.concat(liy)

date= np.array(dtt)
year= np.array(yrr)

dff=pd.DataFrame(df)
dff.rename(columns={0:'NO_Day_ave'},inplace=True)

dff.insert(1, "DOY", date)
dff.insert(2,'YEAR',year)
#***********************************************************
day=dff['DOY']

year=int(yer)

out= pd.to_datetime(day-1, unit='D', origin=str(year))
dff.insert(0,'Date',out)
dfi=dff.sort_values(by=['DOY'])
dfi.to_csv('/directory.file format')
dfi

              Date  NO_Day_ave    DOY    YEAR
NO_IRRF 2015-03-16    0.080683   75.0  2015.0
NO_IRRF 2015-03-17    0.243910   76.0  2015.0
NO_IRRF 2015-03-18    0.423985   77.0  2015.0
NO_IRRF 2015-03-19    0.189090   78.0  2015.0
NO_IRRF 2015-03-20    0.131494   79.0  2015.0
NO_IRRF 2015-03-21    0.109251   80.0  2015.0
NO_IRRF 2015-03-22    0.107724   81.0  2015.0
NO_IRRF 2015-03-23    0.107680   82.0  2015.0
NO_IRRF 2015-03-24    0.087472   83.0  2015.0
NO_IRRF 2015-03-25    0.081347   84.0  2015.0
NO_IRRF 2015-06-01    0.169927  152.0  2013.0
NO_IRRF 2015-06-02    0.129600  153.0  2013.0
NO_IRRF 2015-06-03    0.081426  154.0  2013.0
NO_IRRF 2015-06-04    0.066957  155.0  2013.0
NO_IRRF 2015-09-25    0.062316  268.0  2011.0
NO_IRRF 2015-09-26    0.099132  269.0  2011.0
NO_IRRF 2015-09-27    0.178337  270.0  2011.0
NO_IRRF 2015-09-28    0.131569  271.0  2011.0
NO_IRRF 2015-12-20    0.207782  354.0  2015.0
NO_IRRF 2015-12-21    0.372834  355.0  2015.0
NO_IRRF 2015-12-22    0.163181  356.0  2015.0
NO_IRRF 2015-12-23    0.123174  357.0  2015.0